server:
  port: 53344

spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: git@github.com:mawen12/config-repo.git # git名称
          search-paths: # 搜索目录
            - config-repo
      label: master # 分支

# rabbitmq配置
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest

# 注册到Eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

# 端点配置
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh' # 暴露bus刷新配置端点
