server:
  port: 9002

spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        # nacos集群地址
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'



