server:
  port: 53366

spring:
  application:
    name: config-client
  cloud:
    config: # Config 客户端配置
      label: master # 分支名称
      name: config-repo # 配置文件名称
      profile: dev # 读取后缀名称
        uri: http://localhost:53344 # 配置中心地址

# 服务注册到Eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'